name: 创建发布版本

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: 构建项目
        run: deno task build

      - name: 创建发布版本
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
